fileNamePrefix_MC = "samples/uhh2.AnalysisModuleRunner.MC."
fileNamePrefix_DATA = "samples/uhh2.AnalysisModuleRunner.DATA."

dict_Classes = {
    "tW_signal":{
        "Use":True,
        "File":"ST_tW_signal.root"
    },
    "tW_other":{
        "Use":True,
        "File":"ST_tW_other.root"
    },
    "tW_bkg_TopToHadAndWToTau":{
        "Use":True,
        "File":"ST_tW_bkg_TopToHadAndWToTau.root"
    },
    "tW_bkg_Else":{
        "Use":True,
        "File":"ST_tW_bkg_Else.root"
    },
    "tChannel":{
        "Use":True,
        "File":"ST_non-tW_t-Ch.root"
    },
    "sChannel":{
        "Use":True,
        "File":"ST_non-tW_s-Ch.root"
    },
    "TTbar":{
        "Use":True,
        "File":"TTbar.root"
    },
    "WJets":{
        "Use":True,
        "File":"WJets.root"
    },
    "DYJets":{
        "Use":True,
        "File":"DYJets.root"
    },
    "Diboson":{
        "Use":True,
        "File":"Diboson.root"
    },
    "QCD":{
        "Use":True,
        "File":"QCD.root"
    }
}
